services:
  her:
    image: ghcr.io/c25423/her:latest
    container_name: her
    ports:
      - 3773:3773 # T3 Code
      - 4096:4096 # OpenCode
    security_opt:
      - seccomp=unconfined # Bubblewrap
    stdin_open: true
    tty: true
    volumes:
      - ./claude/.claude.json:/root/.claude.json
      - ./claude/data:/root/.claude
      - ./codex/data:/root/.codex
