services:
  her:
    image: ghcr.io/c25423/her:latest
    container_name: her
    entrypoint: ["zsh", "-c"]
    command: ["opencode web --hostname 127.0.0.1 --port 4096"]
    ports:
      - 3773:3773 # T3 Code
      - 4096:4096 # OpenCode
    security_opt:
      - seccomp=unconfined # Bubblewrap
    stdin_open: true
    tty: true
    volumes:
      - ./codex/data:/root/.codex
      - ./opencode/config:/root/.config/opencode
      - ./opencode/share:/root/.local/share/opencode
      - ./opencode/state:/root/.local/state/opencode
      - ./t3/data:/root/.t3
